### ISSUE TITLE
Why not use sockets instead of tcp for fastcgi_pass

### ISSUE THREAD

**Issue by SudoGetBeer** [Joostvanderlaan/dockerfiles#1]
Hey,
I have read that sockets should be faster. Sure it only applies for high performance, but why not just optimize for that if there is no tradeoff?

Here is a serverfault discussion on that topic.
http://serverfault.com/questions/195328/unix-socket-vs-tcp-ip-hostport

**Comment by Joostvanderlaan** [comment]
Sorry for the late reply, guess I missed your message. You can file a pull request if you want!

**Comment by andrewmclagan** [comment]
agreed, no point in going through the whole TCP stack for no reason.

**Comment by Joostvanderlaan** [comment]
Once more, you can file a Pull Request!
